# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/use
minecraft_version=26.3-pre-3
loader_version=0.19.5
loom_version=1.15-SNAPSHOT

# Fabric API
fabric_api_version=0.160.2+26.3

	# Mod Properties
	mod_version = 3.2.0+26.3
	maven_group = eu.pb4
	archives_base_name = placeholder-api

mc_extra_supported=
