# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/use
	minecraft_version=25w08a
	yarn_mappings=25w08a+build.4
	loader_version=0.16.10

	#Fabric api
	fabric_version=0.118.0+1.21.5

	# Mod Properties
	mod_version = 2.6.0+1.21.5
	maven_group = eu.pb4
	archives_base_name = placeholder-api
